# Alignment
# Syntax transformations.
align_assignment = true
align_conditional = true
align_matrix = true
align_pair_arrow = true
align_struct_field = true
always_for_in = true
always_use_return = true
annotate_untyped_fields_with_any = true
conditional_to_if = true
format_docstrings = true
format_markdown = true
import_to_using = true
indent = 4
indent_submodule = true
join_lines_based_on_source = false
margin = 92
normalize_line_endings = "unix"
overwrite = true
pipe_to_function_call = true
remove_extra_newlines = true
separate_kwargs_with_semicolon = true
short_circuit_to_if = true
short_to_long_function_def = true
style = "yas"
surround_whereop_typeparameters = true
trailing_comma = false
trailing_zero = true
verbose = true
whitespace_in_kwargs = true
whitespace_ops_in_indices = true
whitespace_typedefs = true
