"""
$(DocStringExtensions.README)
"""
module PortfolioOptimisers

using Accessors: Accessors
using ArgCheck: @argcheck
using Base.ScopedValues: ScopedValue
using AverageShiftedHistograms: AverageShiftedHistograms
using Clustering: Clustering, assignments
using Combinatorics: Combinatorics
using ConcreteStructs: @concrete
using DataFrames: DataFrames
using DataStructures: DataStructures
using Dates: Dates
using Distances: Distances
using Distributions: Distributions
using DocStringExtensions: DocStringExtensions
using FLoops: FLoops
using GLM: GLM
using Graphs: Graphs
using InteractiveUtils: InteractiveUtils
using JuMP: JuMP
using LinearAlgebra: LinearAlgebra
using LogExpFunctions: LogExpFunctions
using MultivariateStats: MultivariateStats
using NearestCorrelationMatrix: NearestCorrelationMatrix
using Optim: Optim
using Preferences: Preferences
using Random: Random
using Roots: Roots
using SimpleWeightedGraphs: SimpleWeightedGraphs
using SparseArrays: SparseArrays
using SpecialFunctions: SpecialFunctions
using Statistics: Statistics, mean, std, var, cor, cov
using StatsAPI: StatsAPI, fit, predict
using StatsBase: StatsBase
using StringDistances: StringDistances
using TimeSeries: TimeSeries

#=
# Turn readme into PortfolioOptimisers' docs.
@doc let
    path = joinpath(dirname(@__DIR__), "docs/src/index.md")
    include_dependency(path)
    read(path, String)
end PortfolioOptimisers
=#

#=
# Programmatically include source files
src_files = String[]
sizehint!(src_files, 149)
for (root, dirs, files) in walkdir(@__DIR__)
    for file in files
        if file == "PortfolioOptimisers.jl"
            continue
        end
        push!(src_files, joinpath(root, file))
    end
end
sort!(src_files)
include.(src_files)
=#

include("01_Base/01_DocstringDictionaries.jl")
include("01_Base/02_TypeRoots.jl")
include("01_Base/03_PrettyShow.jl")
include("01_Base/04_ScopedConfig.jl")
include("01_Base/05_Preferences.jl")
include("01_Base/06_Messages.jl")
include("01_Base/07_Errors.jl")
include("01_Base/08_TypeAliases.jl")
include("01_Base/09_ObservationWeights.jl")
include("01_Base/10_Assertions.jl")
include("01_Base/11_VecScalar.jl")
include("01_Base/12_NormError.jl")
include("01_Base/13_KappaLog.jl")
include("01_Base/14_PartialFit.jl")
include("01_Base/15_Online.jl")
include("01_Base/16_CoveragePolicy.jl")
include("02_Tools.jl")
include("03_InputData/01_AssetPanel.jl")
include("03_InputData/02_AssetPanelBuilder.jl")
include("03_InputData/03_ListingSpan.jl")
include("03_InputData/04_Preprocessing.jl")
include("03_InputData/05_CarrierViews.jl")
include("03_InputData/06_PricesResult.jl")
include("03_InputData/07_PriceIngestion.jl")
include("03_InputData/08_PriceGapFill.jl")
include("03_InputData/09_PriceFilters.jl")
include("03_InputData/10_ReturnsResult.jl")
include("03_InputData/11_PricesToReturns.jl")
include("03_InputData/12_TrainTestSplit.jl")
include("03_InputData/13_Base_AssetSelection.jl")
include("03_InputData/14_CrossSectionalTransforms.jl")
include("03_InputData/15_FeatureSelector.jl")
include("03_InputData/16_PanelDataFrame.jl")
include("03_InputData/17_ReturnsBufferState.jl")
include("03_InputData/18_PreprocessingPartialFit.jl")
include("04_MatrixProcessing/01_PosdefMatrix.jl")
include("04_MatrixProcessing/02_Denoise.jl")
include("04_MatrixProcessing/03_Detone.jl")
include("04_MatrixProcessing/04_MatrixProcessing.jl")
include("05_Moments/01_Base_Moments.jl")
include("05_Moments/02_SimpleExpectedReturns.jl")
include("05_Moments/03_Covariance.jl")
include("05_Moments/04_SimpleVariance.jl")
include("05_Moments/05_Gerber/01_GerberCovariance.jl")
include("05_Moments/05_Gerber/02_SmythBrobyCovariance.jl")
include("05_Moments/05_Gerber/03_GerberIQCovariance.jl")
include("05_Moments/06_DistanceCovariance.jl")
include("05_Moments/07_LowerTailDependenceCovariance.jl")
include("05_Moments/08_RankCovariance.jl")
include("05_Moments/09_Histogram.jl")
include("05_Moments/10_MutualInfoCovariance.jl")
include("05_Moments/11_DenoiseCovariance.jl")
include("05_Moments/12_DetoneCovariance.jl")
include("05_Moments/13_ProcessedCovariance.jl")
include("05_Moments/14_PortfolioOptimisersCovariance.jl")
include("05_Moments/15_ShrunkExpectedReturns.jl")
include("05_Moments/16_EquilibriumExpectedReturns.jl")
include("05_Moments/17_ExcessExpectedReturns.jl")
include("05_Moments/18_Coskewness.jl")
include("05_Moments/19_Cokurtosis.jl")
include("05_Moments/20_Base_Regression.jl")
include("05_Moments/21_TimeSeriesRegression/01_StepwiseRegression.jl")
include("05_Moments/21_TimeSeriesRegression/02_DimensionReductionRegression.jl")
include("05_Moments/22_ImpliedVolatility.jl")
include("05_Moments/23_CorrelationCovariance.jl")
include("05_Moments/24_AbstractCovarianceVariance.jl")
include("05_Moments/25_StandardDeviationExpectedReturns.jl")
include("05_Moments/26_Windowed/01_WindowedExpectedReturns.jl")
include("05_Moments/26_Windowed/02_WindowedCovariance.jl")
include("05_Moments/26_Windowed/03_WindowedVariance.jl")
include("05_Moments/26_Windowed/04_WindowedCoskewness.jl")
include("05_Moments/26_Windowed/05_WindowedCokurtosis.jl")
include("05_Moments/27_MedianExpectedReturns.jl")
include("05_Moments/28_CustomValueExpectedReturns.jl")
include("05_Moments/29_ExpWeighted/01_ExpWeightedExpectedReturns.jl")
include("05_Moments/29_ExpWeighted/02_ExpWeightedVariance.jl")
include("05_Moments/29_ExpWeighted/03_ExpWeightedCovariance.jl")
include("05_Moments/30_RegimeAdjusted/01_RegimeAdjustedExpWeightedVariance.jl")
include("05_Moments/30_RegimeAdjusted/02_RegimeAdjustedExpWeightedCovariance.jl")
include("05_Moments/31_HigherMomentPartialFit.jl")
include("05_Moments/32_CrossSectionalFactorModel/01_CrossSectionalRegression.jl")
include("05_Moments/32_CrossSectionalFactorModel/02_CrossSectionalWeights.jl")
include("05_Moments/32_CrossSectionalFactorModel/03_CrossSectionalFactorModel.jl")
include("05_Moments/32_CrossSectionalFactorModel/04_FactorExposures/01_Base_Descriptor.jl")
include("05_Moments/32_CrossSectionalFactorModel/04_FactorExposures/02_PanelFieldDescriptors.jl")
include("05_Moments/32_CrossSectionalFactorModel/04_FactorExposures/03_LagDescriptors.jl")
include("05_Moments/32_CrossSectionalFactorModel/04_FactorExposures/04_EWMeanDescriptors.jl")
include("05_Moments/32_CrossSectionalFactorModel/04_FactorExposures/05_EWVolatilityDescriptors.jl")
include("05_Moments/32_CrossSectionalFactorModel/04_FactorExposures/06_EWBetaDescriptors.jl")
include("05_Moments/32_CrossSectionalFactorModel/04_FactorExposures/07_RollingDescriptors.jl")
include("05_Moments/32_CrossSectionalFactorModel/04_FactorExposures/08_Base_Exposure.jl")
include("05_Moments/32_CrossSectionalFactorModel/04_FactorExposures/09_CompositeExposure.jl")
include("05_Moments/32_CrossSectionalFactorModel/04_FactorExposures/10_DerivedExposure.jl")
include("05_Moments/32_CrossSectionalFactorModel/04_FactorExposures/11_OneHotExposure.jl")
include("05_Moments/32_CrossSectionalFactorModel/04_FactorExposures/12_ConstantExposure.jl")
include("05_Moments/32_CrossSectionalFactorModel/04_FactorExposures/13_ExposureNeutralisation.jl")
include("05_Moments/32_CrossSectionalFactorModel/05_FactorFamilyBasis.jl")
include("05_Moments/32_CrossSectionalFactorModel/06_FactorFamilyBasisTransforms.jl")
include("05_Moments/32_CrossSectionalFactorModel/07_ReturnForecasts/01_Base_ReturnForecast.jl")
include("05_Moments/32_CrossSectionalFactorModel/07_ReturnForecasts/02_DescriptorScores.jl")
include("05_Moments/32_CrossSectionalFactorModel/07_ReturnForecasts/03_CustomValueReturnForecast.jl")
include("05_Moments/32_CrossSectionalFactorModel/07_ReturnForecasts/04_FixedWeightedReturnForecast.jl")
include("05_Moments/32_CrossSectionalFactorModel/07_ReturnForecasts/05_ExpWeightedReturnForecast.jl")
include("05_Moments/32_CrossSectionalFactorModel/07_ReturnForecasts/06_TargetReturnForecast.jl")
include("05_Moments/32_CrossSectionalFactorModel/07_ReturnForecasts/07_ForecastEvaluation.jl")
include("05_Moments/32_CrossSectionalFactorModel/07_ReturnForecasts/08_ForecastHistory.jl")
include("05_Moments/32_CrossSectionalFactorModel/07_ReturnForecasts/09_ForecastInformationCoefficient.jl")
include("05_Moments/32_CrossSectionalFactorModel/07_ReturnForecasts/10_ForecastPortfolios.jl")
include("05_Moments/32_CrossSectionalFactorModel/07_ReturnForecasts/11_ForecastFactorCorrelation.jl")
include("05_Moments/32_CrossSectionalFactorModel/07_ReturnForecasts/12_ForecastForwardWindows.jl")
include("05_Moments/32_CrossSectionalFactorModel/07_ReturnForecasts/13_ForecastCalibration.jl")
include("05_Moments/32_CrossSectionalFactorModel/07_ReturnForecasts/14_ForecastSummary.jl")
include("05_Moments/32_CrossSectionalFactorModel/08_CrossSectionalRegressionDiagnostics.jl")
include("05_Moments/32_CrossSectionalFactorModel/09_CrossSectionalExposureDiagnostics.jl")
include("05_Moments/32_CrossSectionalFactorModel/10_FactorModelSummary.jl")
include("05_Moments/32_CrossSectionalFactorModel/11_CrossSectionalIdiosyncraticDiagnostics.jl")
include("05_Moments/33_CoverageUniverse.jl")
include("05_Moments/34_PriceLevelExpectedReturns.jl")
include("05_Moments/35_CompositePriceLevelStatistics.jl")
include("05_Moments/36_RankOneCovariance.jl")
include("06_Distance/01_Base_Distance.jl")
include("06_Distance/02_Distance.jl")
include("06_Distance/03_DistanceDistance.jl")
include("06_Distance/04_Similarity.jl")
include("06_Distance/05_FeatureDistance.jl")
include("07_JuMPModelOptimisation.jl")
include("08_Phylogeny/01_Base_Phylogeny.jl")
include("08_Phylogeny/02_Clusters.jl")
include("08_Phylogeny/03_Hierarchical.jl")
include("08_Phylogeny/04_NonHierarchicalClustering.jl")
include("08_Phylogeny/05_Phylogeny.jl")
include("08_Phylogeny/06_DBHT/01_DBHT.jl")
include("08_Phylogeny/06_DBHT/02_PMFG.jl")
include("08_Phylogeny/06_DBHT/03_GraphTraversal.jl")
include("08_Phylogeny/06_DBHT/04_CliqueHierarchy.jl")
include("08_Phylogeny/06_DBHT/05_BubbleTree.jl")
include("08_Phylogeny/06_DBHT/06_DBHTDendrogram.jl")
include("08_Phylogeny/06_DBHT/07_DBHTClustering.jl")
include("08_Phylogeny/07_LoGo.jl")
include("08_Phylogeny/08_Network/01_MinimumSpanningTree.jl")
include("08_Phylogeny/08_Network/02_NetworkEstimator.jl")
include("08_Phylogeny/08_Network/03_NetworkGraph.jl")
include("08_Phylogeny/08_Network/04_Separation.jl")
include("08_Phylogeny/09_Centrality/01_Centrality.jl")
include("08_Phylogeny/09_Centrality/02_CentralityPolarity.jl")
include("08_Phylogeny/09_Centrality/03_CentralityEstimator.jl")
include("08_Phylogeny/09_Centrality/04_CentralityQueries.jl")
include("08_Phylogeny/10_PhylogenyClustering.jl")
include("08_Phylogeny/11_PhylogenyMatrix.jl")
include("08_Phylogeny/12_AssetPhylogeny.jl")
include("09_ConstraintGeneration/01_Base_ConstraintGeneration.jl")
include("09_ConstraintGeneration/02_LinearConstraintGeneration.jl")
include("09_ConstraintGeneration/03_RiskBudgetConstraintGeneration.jl")
include("09_ConstraintGeneration/04_PhylogenyConstraintGeneration.jl")
include("09_ConstraintGeneration/05_WeightBoundsConstraintGeneration.jl")
include("09_ConstraintGeneration/06_AssetSetsMatrix.jl")
include("09_ConstraintGeneration/07_ThresholdConstraintGeneration.jl")
include("09_ConstraintGeneration/08_ExposureConstraintGeneration.jl")
include("09_ConstraintGeneration/09_CrossSectionalFactorAxis.jl")
include("10_Prior/01_Base_Prior.jl")
include("10_Prior/02_EmpiricalPrior.jl")
include("10_Prior/03_FactorPrior.jl")
include("10_Prior/04_HighOrderPrior.jl")
include("10_Prior/05_BlackLitterman/01_BlackLittermanViewsGeneration.jl")
include("10_Prior/05_BlackLitterman/02_BlackLittermanPrior.jl")
include("10_Prior/05_BlackLitterman/03_BayesianBlackLittermanPrior.jl")
include("10_Prior/05_BlackLitterman/04_FactorBlackLittermanPrior.jl")
include("10_Prior/05_BlackLitterman/05_AugmentedBlackLittermanPrior.jl")
include("10_Prior/06_EntropyPooling/01_Base_EntropyPoolingPrior.jl")
include("10_Prior/06_EntropyPooling/02_MeucciEntropyPoolingPrior.jl")
include("10_Prior/06_EntropyPooling/03_EntropyPoolingPrior.jl")
include("10_Prior/07_OpinionPoolingPrior.jl")
include("10_Prior/08_HighOrderFactorPriorEstimator.jl")
include("10_Prior/09_AssetPanelEstimators.jl")
include("10_Prior/10_Base_CrossSectionalFactorPrior.jl")
include("10_Prior/11_CrossSectionalFactorPrior.jl")
include("10_Prior/12_PriorPartialFit.jl")
include("10_Prior/13_PriorExpectedReturns.jl")
include("11_UncertaintySets/01_Base_UncertaintySets.jl")
include("11_UncertaintySets/02_DeltaUncertaintySets.jl")
include("11_UncertaintySets/03_NormalUncertaintySets.jl")
include("11_UncertaintySets/04_BootstrapUncertaintySets.jl")
include("11_UncertaintySets/05_L1UncertaintySets.jl")
include("11_UncertaintySets/06_CalibrationRules.jl")
include("11_UncertaintySets/07_CompactUncertaintySets.jl")
include("11_UncertaintySets/08_NormBallUncertaintySets.jl")
include("11_UncertaintySets/09_OrthogonalUncertaintySets.jl")
include("11_UncertaintySets/10_CompactRadiusRules.jl")
include("12_Turnover.jl")
include("13_Fees.jl")
include("14_NetReturnsDrawdowns.jl")
include("15_Tracking.jl")
include("16_RiskMeasures/01_Base_RiskMeasures.jl")
include("16_RiskMeasures/02_Variance.jl")
include("16_RiskMeasures/03_MomentRiskMeasures.jl")
include("16_RiskMeasures/04_Kurtosis.jl")
include("16_RiskMeasures/05_NegativeSkewness.jl")
include("16_RiskMeasures/06_XatRisk/01_XatRisk.jl")
include("16_RiskMeasures/06_XatRisk/02_ConditionalXatRisk.jl")
include("16_RiskMeasures/06_XatRisk/03_EntropicXatRisk.jl")
include("16_RiskMeasures/06_XatRisk/04_RelativisticXatRisk.jl")
include("16_RiskMeasures/06_XatRisk/05_PowerNormXatRisk.jl")
include("16_RiskMeasures/07_OWARiskMeasures.jl")
include("16_RiskMeasures/08_AverageDrawdown.jl")
include("16_RiskMeasures/09_UlcerIndex.jl")
include("16_RiskMeasures/10_MaximumDrawdown.jl")
include("16_RiskMeasures/11_BrownianDistanceVariance.jl")
include("16_RiskMeasures/12_WorstRealisation.jl")
include("16_RiskMeasures/13_NoRisk.jl")
include("16_RiskMeasures/14_Range.jl")
include("16_RiskMeasures/15_TurnoverRiskMeasure.jl")
include("16_RiskMeasures/16_TrackingRiskMeasure.jl")
include("16_RiskMeasures/17_VarianceSkewKurtosis.jl")
include("16_RiskMeasures/18_GenericValueatRiskRange.jl")
include("16_RiskMeasures/19_RatioRiskMeasure.jl")
include("16_RiskMeasures/20_EqualRiskMeasure.jl")
include("16_RiskMeasures/21_MedianAbsoluteDeviationRisk.jl")
include("16_RiskMeasures/22_NonOptimisationRiskMeasures.jl")
include("16_RiskMeasures/23_AdjustRiskContributions.jl")
include("16_RiskMeasures/24_ExpectedRisk.jl")
include("16_RiskMeasures/25_RiskMeasureTools.jl")
include("17_Optimisation/01_Base_Optimisation.jl")
include("17_Optimisation/02_CrossValidation/01_Base_CrossValidation.jl")
include("17_Optimisation/02_CrossValidation/02_KFold.jl")
include("17_Optimisation/02_CrossValidation/03_Combinatorial.jl")
include("17_Optimisation/02_CrossValidation/04_WalkForward.jl")
include("17_Optimisation/02_CrossValidation/05_MultipleRandomised.jl")
include("17_Optimisation/02_CrossValidation/06_Validation.jl")
include("17_Optimisation/02_CrossValidation/07_Scoring.jl")
include("17_Optimisation/02_CrossValidation/08_OptimisationCrossValidation.jl")
include("17_Optimisation/02_CrossValidation/09_Base_SearchCrossValidation.jl")
include("17_Optimisation/02_CrossValidation/10_GridSearchCrossValidation.jl")
include("17_Optimisation/02_CrossValidation/11_RandomisedSearchCrossValidation.jl")
include("17_Optimisation/02_CrossValidation/12_OnlineFoldLoop.jl")
include("17_Optimisation/02_CrossValidation/13_CovarianceForecastEvaluation.jl")
include("17_Optimisation/02_CrossValidation/14_CovarianceForecastSummary.jl")
include("17_Optimisation/02_CrossValidation/15_Resume.jl")
include("17_Optimisation/02_CrossValidation/16_LogWealthRegret.jl")
include("17_Optimisation/03_NaiveOptimisation.jl")
include("17_Optimisation/04_Hierarchical/01_Base_ClusteringOptimisation.jl")
include("17_Optimisation/04_Hierarchical/02_HierarchicalRiskParity.jl")
include("17_Optimisation/04_Hierarchical/03_SchurComplementHierarchicalRiskParity.jl")
include("17_Optimisation/04_Hierarchical/04_HierarchicalEqualRiskContribution.jl")
include("17_Optimisation/05_JuMP/01_Base_JuMPOptimisation.jl")
include("17_Optimisation/05_JuMP/02_JuMPConstraints/01_MIPIndicators.jl")
include("17_Optimisation/05_JuMP/02_JuMPConstraints/02_Returns_and_ObjectiveFunctions.jl")
include("17_Optimisation/05_JuMP/02_JuMPConstraints/03_BudgetConstraints.jl")
include("17_Optimisation/05_JuMP/02_JuMPConstraints/04_WeightConstraints.jl")
include("17_Optimisation/05_JuMP/02_JuMPConstraints/05_SDPConstraints.jl")
include("17_Optimisation/05_JuMP/02_JuMPConstraints/06_IntegerPhylogenyConstraints.jl")
include("17_Optimisation/05_JuMP/02_JuMPConstraints/07_CardinalityConstraints.jl")
include("17_Optimisation/05_JuMP/02_JuMPConstraints/08_ThresholdConstraints.jl")
include("17_Optimisation/05_JuMP/02_JuMPConstraints/09_TurnoverConstraints.jl")
include("17_Optimisation/05_JuMP/02_JuMPConstraints/10_FeesConstraints.jl")
include("17_Optimisation/05_JuMP/02_JuMPConstraints/11_TrackingErrorConstraints.jl")
include("17_Optimisation/05_JuMP/02_JuMPConstraints/12_RegularisationConstraints.jl")
include("17_Optimisation/05_JuMP/02_JuMPConstraints/13_WeightNormConstraints.jl")
include("17_Optimisation/05_JuMP/03_JuMPOptimiser.jl")
include("17_Optimisation/05_JuMP/04_MeanRisk.jl")
include("17_Optimisation/05_JuMP/05_FactorRiskContribution.jl")
include("17_Optimisation/05_JuMP/06_NearOptimalCentering.jl")
include("17_Optimisation/05_JuMP/07_RiskBudgeting.jl")
include("17_Optimisation/05_JuMP/08_RelaxedRiskBudgeting.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/01_BaseRiskConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/02_VarianceConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/03_MomentRiskMeasureConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/04_KurtosisConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/05_NegativeSkewnessConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/06_XatRisk/01_XatRiskConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/06_XatRisk/02_ConditionalXatRiskConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/06_XatRisk/03_EntropicXatRiskConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/06_XatRisk/04_RelativisticXatRiskConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/06_XatRisk/05_PowerNormXatRiskConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/07_OWARiskMeasuresConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/08_AverageDrawdownConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/09_UlcerIndexConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/10_MaximumDrawdownConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/11_BrownianDistanceVarianceConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/12_WorstRealisationConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/13_NoRiskConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/14_RangeConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/15_TurnoverRiskMeasureConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/16_TrackingRiskMeasureConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/17_VarianceSkewKurtosisConstraints.jl")
include("17_Optimisation/05_JuMP/09_RiskMeasureConstraints/18_GenericValueatRiskRangeConstraints.jl")
include("17_Optimisation/06_Meta/01_Base_MetaOptimisation.jl")
include("17_Optimisation/06_Meta/02_NestedClustered.jl")
include("17_Optimisation/06_Meta/03_Stacking.jl")
include("17_Optimisation/06_Meta/04_SubsetResampling.jl")
include("17_Optimisation/07_FiniteAllocation/01_Base_FiniteAllocation.jl")
include("17_Optimisation/07_FiniteAllocation/02_DiscreteFiniteAllocation.jl")
include("17_Optimisation/07_FiniteAllocation/03_GreedyFiniteAllocation.jl")
include("17_Optimisation/08_RiskMeasureCompatibility.jl")
include("17_Optimisation/09_OnlineOptimisation.jl")
include("17_Optimisation/10_OnlinePortfolioSelection/01_Base_OnlinePortfolioSelection.jl")
include("17_Optimisation/10_OnlinePortfolioSelection/02_OnlineSelectionRules.jl")
include("17_Optimisation/10_OnlinePortfolioSelection/03_OnlinePortfolioSelection.jl")
include("17_Optimisation/10_OnlinePortfolioSelection/04_ProgrammeAllocationSet.jl")
include("17_Optimisation/10_OnlinePortfolioSelection/05_ForecastRules.jl")
include("17_Optimisation/10_OnlinePortfolioSelection/06_SecondSetRules.jl")
include("17_Optimisation/10_OnlinePortfolioSelection/07_MirrorDescent.jl")
include("17_Optimisation/10_OnlinePortfolioSelection/08_FollowTheLeader.jl")
include("18_ExpectedReturns.jl")
include("19_FactorAttribution/01_FactorAttribution.jl")
include("19_FactorAttribution/02_FactorAttributionRealised.jl")
include("20_AssetSelection.jl")
include("21_Pipeline/01_Base_Pipeline.jl")
include("21_Pipeline/02_StepExecution.jl")
include("21_Pipeline/03_Pipeline.jl")
include("21_Pipeline/04_PredictionCV.jl")
include("21_Pipeline/05_SearchCrossValidation.jl")
include("21_Pipeline/06_OnlinePipeline.jl")
include("22_Plotting.jl")
include("23_Aliases.jl")

# Every `@propagatable` struct is declared by now, and so is every outer keyword
# constructor, so the contract behind the generated `factory`/`port_opt_view` methods is
# checked at the declaration instead of at the first call. Runs at precompile time only.
check_propagatable_contracts()
# The propagation tag set is data. A row of `PROP_TAG_NAMES` that lacks a stub macro, a
# field transform, or a channel is a tag that parses and never propagates, so it is refused
# here rather than at the first `factory` call. Runs at precompile time only.
check_prop_tag_macros()
end
