module PortfolioOptimisers

using ArgCheck, AverageShiftedHistograms, Clustering, Distances, Distributions, FLoops, GLM,
      Impute, InteractiveUtils, Interfaces, JuMP, LinearAlgebra, LogExpFunctions,
      MultivariateStats, NearestCorrelationMatrix, Optim, Graphs, SimpleWeightedGraphs,
      StatsAPI, PythonCall, PrecompileTools, Random, Roots, SparseArrays, Statistics,
      StatsBase, DataFrames, TimeSeries

# Turn readme into PortfolioOptimisers' docs.
@doc let
    path = joinpath(dirname(@__DIR__), "docs/src/index.md")
    include_dependency(path)
    read(path, String)
end PortfolioOptimisers

# # 111 files.
# src_files = String[]
# sizehint!(src_files, 111)
# for (root, dirs, files) in walkdir(@__DIR__)
#     for file in files
#         if file == "PortfolioOptimisers.jl"
#             continue
#         end
#         push!(src_files, joinpath(root, file))
#     end
# end
# sort!(src_files)
# include.(src_files)

include("01_Base.jl")
include("02_Tools.jl")
include("03_Preprocessing.jl")
include("04_PosdefMatrix.jl")
include("05_Denoise.jl")
include("06_Detone.jl")
include("07_MatrixProcessing.jl")
include("08_Moments/01_Base_Moments.jl")
include("08_Moments/02_SimpleExpectedReturns.jl")
include("08_Moments/03_Covariance.jl")
include("08_Moments/04_SimpleVariance.jl")
include("08_Moments/05_GerberCovariances.jl")
include("08_Moments/06_SmythBrobyCovariance.jl")
include("08_Moments/07_DistanceCovariance.jl")
include("08_Moments/08_LTDCovariance.jl")
include("08_Moments/09_RankCovariance.jl")
include("08_Moments/10_Histogram.jl")
include("08_Moments/11_MutualInfoCovariance.jl")
include("08_Moments/12_PortfolioOptimisersCovariance.jl")
include("08_Moments/13_ShrunkExpectedReturns.jl")
include("08_Moments/14_EquilibriumExpectedReturns.jl")
include("08_Moments/15_ExcessExpectedReturns.jl")
include("08_Moments/16_Coskewness.jl")
include("08_Moments/17_Cokurtosis.jl")
include("08_Moments/18_Base_Regression.jl")
include("08_Moments/19_StepwiseRegression.jl")
include("08_Moments/20_DimensionReductionRegression.jl")
include("08_Moments/21_ImpliedVolatility.jl")
include("09_Distance/01_Base_Distance.jl")
include("09_Distance/02_Distance.jl")
include("09_Distance/03_DistanceDistance.jl")
include("10_JuMPModelOptimisation.jl")
include("11_OWA.jl")
include("12_Phylogeny/01_Base_Phylogeny.jl")
include("12_Phylogeny/02_Clustering.jl")
include("12_Phylogeny/03_Hierarchical.jl")
include("12_Phylogeny/04_DBHT.jl")
include("12_Phylogeny/05_Phylogeny.jl")
include("13_ConstraintGeneration/01_Base_ConstraintGeneration.jl")
include("13_ConstraintGeneration/02_LinearConstraintGeneration.jl")
include("13_ConstraintGeneration/03_PhylogenyConstraintGeneration.jl")
include("13_ConstraintGeneration/04_WeightBoundsConstraintGeneration.jl")
include("13_ConstraintGeneration/05_ThresholdConstraintGeneration.jl")
include("14_Prior/01_Base_Prior.jl")
include("14_Prior/02_EmpiricalPrior.jl")
include("14_Prior/03_FactorPrior.jl")
include("14_Prior/04_HighOrderPrior.jl")
include("14_Prior/05_BlackLittermanViewsGeneration.jl")
include("14_Prior/06_BlackLittermanPrior.jl")
include("14_Prior/07_BayesianBlackLittermanPrior.jl")
include("14_Prior/08_FactorBlackLittermanPrior.jl")
include("14_Prior/09_AugmentedBlackLittermanPrior.jl")
include("14_Prior/10_EntropyPoolingPrior.jl")
include("14_Prior/11_OpinionPoolingPrior.jl")
include("15_UncertaintySets/01_Base_UncertaintySets.jl")
include("15_UncertaintySets/02_DeltaUncertaintySets.jl")
include("15_UncertaintySets/03_NormalUncertaintySets.jl")
include("15_UncertaintySets/04_BootstrapUncertaintySets.jl")
include("16_Turnover.jl")
include("17_Fees.jl")
include("18_Tracking.jl")
include("19_RiskMeasures/01_Base_RiskMeasures.jl")
include("19_RiskMeasures/02_Variance.jl")
include("19_RiskMeasures/03_MomentRiskMeasures.jl")
include("19_RiskMeasures/04_SquareRootKurtosis.jl")
include("19_RiskMeasures/05_NegativeSkewness.jl")
include("19_RiskMeasures/06_XatRisk.jl")
include("19_RiskMeasures/07_ConditionalXatRisk.jl")
include("19_RiskMeasures/08_EntropicXatRisk.jl")
include("19_RiskMeasures/09_RelativisticXatRisk.jl")
include("19_RiskMeasures/10_OWARiskMeasures.jl")
include("19_RiskMeasures/11_AverageDrawdown.jl")
include("19_RiskMeasures/12_UlcerIndex.jl")
include("19_RiskMeasures/13_MaximumDrawdown.jl")
include("19_RiskMeasures/14_BrownianDistanceVariance.jl")
include("19_RiskMeasures/15_WorstRealisation.jl")
include("19_RiskMeasures/16_Range.jl")
include("19_RiskMeasures/17_EqualRiskMeasure.jl")
include("19_RiskMeasures/18_TurnoverRiskMeasure.jl")
include("19_RiskMeasures/19_TrackingRiskMeasure.jl")
include("19_RiskMeasures/20_RatioRiskMeasure.jl")
include("19_RiskMeasures/21_NoOptimisationRiskMeasures.jl")
include("19_RiskMeasures/22_AdjustRiskContributions.jl")
include("19_RiskMeasures/23_ExpectedRisk.jl")
include("19_RiskMeasures/24_RiskMeasureTools.jl")
include("20_Optimisation/01_Base_Optimisation.jl")
include("20_Optimisation/02_Base_ClusteringOptimisation.jl")
include("20_Optimisation/03_HierarchicalOptimiser.jl")
include("20_Optimisation/04_HierarchicalRiskParity.jl")
include("20_Optimisation/05_HierarchicalEqualRiskContribution.jl")
include("20_Optimisation/06_Base_JuMPOptimisation.jl")
include("20_Optimisation/07_Returns_and_ObjectiveFunctions.jl")
include("20_Optimisation/08_JuMPConstraints.jl")
include("20_Optimisation/09_JuMPOptimiser.jl")
include("20_Optimisation/10_MeanRisk.jl")
include("20_Optimisation/11_FactorRiskContribution.jl")
include("20_Optimisation/12_NearOptimalCentering.jl")
include("20_Optimisation/13_RiskBudgeting.jl")
include("20_Optimisation/14_RelaxedRiskBudgeting.jl")
include("20_Optimisation/15_NestedClustered.jl")
include("20_Optimisation/16_Stacking.jl")
include("20_Optimisation/17_RiskConstraints.jl")
include("20_Optimisation/18_Base_FiniteAllocation.jl")
include("20_Optimisation/19_GreedyFiniteAllocation.jl")
include("20_Optimisation/20_DiscreteFiniteAllocation.jl")
include("20_Optimisation/21_NaiveOptimisation.jl")
include("20_Optimisation/22_SchurComplementHierarchicalRiskParity.jl")
include("21_Expected_Returns.jl")
include("22_Plotting.jl")
include("23_Interfaces.jl")
include("24_Precompilation.jl")

end
