name: Aqua on PRs

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "ext/**"
      - "examples/**"
      - "*.toml"
    types: [opened, synchronize, reopened]

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - uses: actions/checkout@v5
      - name: Aqua
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.add(PackageSpec(name="Aqua"))
          Pkg.develop(PackageSpec(path=pwd()))
          using PortfolioOptimisers, Aqua
          Aqua.test_ambiguities(PortfolioOptimisers)
          Aqua.test_unbound_args(PortfolioOptimisers)
          Aqua.test_undefined_exports(PortfolioOptimisers)
          Aqua.test_project_extras(PortfolioOptimisers)
          Aqua.test_stale_deps(PortfolioOptimisers)
          Aqua.test_piracies(PortfolioOptimisers)
          Aqua.test_persistent_tasks(PortfolioOptimisers)
          Aqua.test_deps_compat(PortfolioOptimisers)